services:
  - type: web
    name: nexusvn
    runtime: php
    buildCommand: |
      echo "No build needed"
    startCommand: php -S 0.0.0.0:$PORT -t .
    plan: free
    envVars:
      - key: DB_HOST
        value: pg-35afdf80-xuanbach21122011-9329.l.aivencloud.com
      - key: DB_PORT
        value: 18543
      - key: DB_NAME
        value: defaultdb
      - key: DB_USER
        value: avnadmin
      - key: DB_PASS
        value: AVNS_gMFjbX8aO2_bbVVOK6b